export const APPWRITE_JWT_KEY = process.env.NEXT_PUBLIC_APPWRITE_JWT_KEY;
export const APPWRITE_URL = process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT;
export const APPWRITE_PROJECT = process.env.NEXT_PUBLIC_PROJECT_ID;
export const PROJECT_DATABASE_ID = process.env.NEXT_PUBLIC_PROJECT_DATABASE_ID;

export const AUTH_USERPROFILE_FUNCTION_ID = process.env.NEXT_PUBLIC_AUTH_USERPROFILE_FUNCTION_ID


export const FUNDS_COLLECTION_ID = process.env.NEXT_PUBLIC_FUNDS_COLLECTION_ID;
export const FUNDING_PROJECTS_COLLECTION_ID = process.env.NEXT_PUBLIC_FUNDING_PROJECTS_COLLECTION_ID;
export const FUNDING_REPORTS_COLLECTION_ID = process.env.NEXT_PUBLIC_FUNDING_REPORTS_COLLECTION_ID;
export const ORDERS_COLLECTION_ID = process.env.NEXT_PUBLIC_ORDERS_COLLECTION_ID;
export const TRANSACTIONS_COLLECTION_ID = process.env.NEXT_PUBLIC_TRANSACTIONS_COLLECTION_ID;
export const INVENTORIES_COLLECTION_ID = process.env.NEXT_PUBLIC_INVENTORIES_COLLECTION_ID;
export const PRODUCTS_COLLECTION_ID = process.env.NEXT_PUBLIC_PRODUCTS_COLLECTION_ID;
export const CROPS_COLLECTION_ID = process.env.NEXT_PUBLIC_CROPS_COLLECTION_ID;
export const RESEARCH_ARCHIVES_COLLECTION_ID = process.env.NEXT_PUBLIC_RESEARCH_ARCHIVES_COLLECTION_ID;
export const STAKEHOLDERS_COLLECTION_ID = process.env.NEXT_PUBLIC_STAKEHOLDERS_COLLECTION_ID;
export const INVESTORS_COLLECTION_ID = process.env.NEXT_PUBLIC_INVESTORS_COLLECTION_ID;
export const LOCATIONS_COLLECTION_ID = process.env.NEXT_PUBLIC_LOCATIONS_COLLECTION_ID;
export const FARMERS_COLLECTION_ID = process.env.NEXT_PUBLIC_FARMERS_COLLECTION_ID;
export const USERS_COLLECTION_ID = process.env.NEXT_PUBLIC_USERS_COLLECTION_ID;
export const EVENTS_COLLECTION_ID = process.env.NEXT_PUBLIC_EVENTS_COLLECTION_ID;
